// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var Data_Lens_Lens = require("../Data.Lens.Lens");
var Data_Void = require("../Data.Void");
var Data_Function = require("../Data.Function");
var devoid = function (dictStrong) {
    return Data_Lens_Lens.lens(Data_Void.absurd)(Data_Function["const"])(dictStrong);
};
module.exports = {
    devoid: devoid
};
