sudo: false
language: haskell
ghc: 7.8
before_install:
- gem install compass
install:
- npm install
- cabal install --only-dependencies --enable-tests
script:
- npm test
- $HOME/.cabal/bin/hlint server/src
- cabal configure --enable-tests && cabal build && cabal test
cache:
  bundler: true
  directories:
  - node_modules
  - bower_components
  - $HOME/.cabal
