sudo: false
language: haskell
before_install:
- gem install compass
install:
- npm install
- cabal sandbox init
- cabal install --only-dependencies --enable-tests
script:
- npm test
- ./.cabal-sandbox/bin/hlint server/src
- cabal configure --enable-tests && cabal test
cache:
  bundler: true
  directories:
  - node_modules
  - bower_components
  - .cabal-sandbox
