// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var Data_Tuple_Nested = require("../Data.Tuple.Nested");
var CSS_Color = require("../CSS.Color");
var CSS_Property = require("../CSS.Property");
var CSS_Size = require("../CSS.Size");
var CSS_String = require("../CSS.String");
var CSS_Stylesheet = require("../CSS.Stylesheet");
var Data_Function = require("../Data.Function");
var Stroke = function (x) {
    return x;
};
var wavy = Data_Function.apply(Stroke)(CSS_String.fromString(CSS_Property.isStringValue)("wavy"));
var valStroke = new CSS_Property.Val(function (v) {
    return v;
});
var solid = Data_Function.apply(Stroke)(CSS_String.fromString(CSS_Property.isStringValue)("solid"));
var ridge = Data_Function.apply(Stroke)(CSS_String.fromString(CSS_Property.isStringValue)("ridge"));
var outset = Data_Function.apply(Stroke)(CSS_String.fromString(CSS_Property.isStringValue)("outset"));
var inset = Data_Function.apply(Stroke)(CSS_String.fromString(CSS_Property.isStringValue)("inset"));
var groove = Data_Function.apply(Stroke)(CSS_String.fromString(CSS_Property.isStringValue)("groove"));
var $$double = Data_Function.apply(Stroke)(CSS_String.fromString(CSS_Property.isStringValue)("double"));
var dotted = Data_Function.apply(Stroke)(CSS_String.fromString(CSS_Property.isStringValue)("dotted"));
var dashed = Data_Function.apply(Stroke)(CSS_String.fromString(CSS_Property.isStringValue)("dashed"));
var borderRadius = function (a) {
    return function (b) {
        return function (c) {
            return function (d) {
                return CSS_Stylesheet.key(CSS_Property.valTuple(CSS_Property.valTuple(CSS_Property.valTuple(CSS_Size.valSize)(CSS_Size.valSize))(CSS_Size.valSize))(CSS_Size.valSize))(CSS_String.fromString(CSS_Property.isStringKey)("border-radius"))(Data_Tuple_Nested.tuple4(a)(b)(c)(d));
            };
        };
    };
};
var borderColor = Data_Function.apply(CSS_Stylesheet.key(CSS_Property.valColor))(CSS_String.fromString(CSS_Property.isStringKey)("border-color"));
var border = function (a) {
    return function (b) {
        return function (c) {
            return Data_Function.apply(CSS_Stylesheet.key(CSS_Property.valTuple(CSS_Property.valTuple(valStroke)(CSS_Size.valSize))(CSS_Property.valColor))(CSS_String.fromString(CSS_Property.isStringKey)("border")))(Data_Tuple_Nested.tuple3(a)(b)(c));
        };
    };
};
module.exports = {
    Stroke: Stroke, 
    border: border, 
    borderColor: borderColor, 
    borderRadius: borderRadius, 
    dashed: dashed, 
    dotted: dotted, 
    "double": $$double, 
    groove: groove, 
    inset: inset, 
    outset: outset, 
    ridge: ridge, 
    solid: solid, 
    wavy: wavy, 
    valStroke: valStroke
};
