// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var CSS_Selector = require("../CSS.Selector");
var CSS_String = require("../CSS.String");
var hover = CSS_String.fromString(CSS_Selector.isStringRefinement)(":hover");
module.exports = {
    hover: hover
};
