// Generated by psc version 0.9.3
"use strict";
var $foreign = require("./foreign");
var Prelude = require("../Prelude");
var Control_Bind = require("../Control.Bind");
var Control_Monad_Aff = require("../Control.Monad.Aff");
var Control_Monad_Aff_AVar = require("../Control.Monad.Aff.AVar");
var Control_Monad_Eff = require("../Control.Monad.Eff");
var Control_Monad_Eff_Class = require("../Control.Monad.Eff.Class");
var Control_Monad_Eff_Exception = require("../Control.Monad.Eff.Exception");
var Control_Monad_Eff_Ref = require("../Control.Monad.Eff.Ref");
var Control_Monad_Error_Class = require("../Control.Monad.Error.Class");
var Data_Array = require("../Data.Array");
var Data_Either = require("../Data.Either");
var Data_Foldable = require("../Data.Foldable");
var Data_Foreign = require("../Data.Foreign");
var Data_Function = require("../Data.Function");
var Data_Function_Uncurried = require("../Data.Function.Uncurried");
var Data_HTTP_Method_1 = require("../Data.HTTP.Method");
var Data_HTTP_Method_1 = require("../Data.HTTP.Method");
var Data_Int = require("../Data.Int");
var Data_Maybe = require("../Data.Maybe");
var Data_MediaType = require("../Data.MediaType");
var Data_Nullable = require("../Data.Nullable");
var Data_Tuple = require("../Data.Tuple");
var $$Math = require("../Math");
var DOM_XHR_Types = require("../DOM.XHR.Types");
var Network_HTTP_Affjax_Request = require("../Network.HTTP.Affjax.Request");
var Network_HTTP_Affjax_Response = require("../Network.HTTP.Affjax.Response");
var Network_HTTP_RequestHeader = require("../Network.HTTP.RequestHeader");
var Network_HTTP_ResponseHeader = require("../Network.HTTP.ResponseHeader");
var Network_HTTP_StatusCode = require("../Network.HTTP.StatusCode");
var Data_Functor = require("../Data.Functor");
var Data_Semiring = require("../Data.Semiring");
var Control_Applicative = require("../Control.Applicative");
var Control_Semigroupoid = require("../Control.Semigroupoid");
var Data_Ring = require("../Data.Ring");
var Data_Show = require("../Data.Show");
var Data_HeytingAlgebra = require("../Data.HeytingAlgebra");
var Data_BooleanAlgebra = require("../Data.BooleanAlgebra");
var Data_Eq = require("../Data.Eq");
var retry = function (dictRequestable) {
    return function (policy) {
        return function (run) {
            return function (req) {
                var retryState = function (v) {
                    if (v instanceof Data_Either.Left) {
                        return Data_Function.apply(Data_Either.Left.create)(new Data_Either.Left(v.value0));
                    };
                    if (v instanceof Data_Either.Right) {
                        if (v.value0.status === 200) {
                            return new Data_Either.Right(v.value0);
                        };
                        var $37 = policy.shouldRetryWithStatusCode(v.value0.status);
                        if ($37) {
                            return Data_Function.apply(Data_Either.Left.create)(new Data_Either.Right(v.value0));
                        };
                        if (!$37) {
                            return new Data_Either.Right(v.value0);
                        };
                        throw new Error("Failed pattern match at Network.HTTP.Affjax line 220, column 11 - line 223, column 23: " + [ $37.constructor.name ]);
                    };
                    throw new Error("Failed pattern match at Network.HTTP.Affjax line 215, column 5 - line 215, column 44: " + [ v.constructor.name ]);
                };
                var go = function (failureRef) {
                    return function (n) {
                        return Control_Bind.bind(Control_Monad_Aff.bindAff)(Data_Functor.map(Control_Monad_Aff.functorAff)(retryState)(Control_Monad_Aff.attempt(run(req))))(function (v) {
                            if (v instanceof Data_Either.Left) {
                                return Control_Bind.bind(Control_Monad_Aff.bindAff)(Data_Function.apply(Control_Monad_Eff_Class.liftEff(Control_Monad_Aff.monadEffAff))(Data_Function.apply(Control_Monad_Eff_Ref.writeRef(failureRef))(new Data_Maybe.Just(v.value0))))(function () {
                                    return Data_Function.apply(Control_Monad_Aff["later'"](policy.delayCurve(n)))(go(failureRef)(n + 1 | 0));
                                });
                            };
                            if (v instanceof Data_Either.Right) {
                                return Control_Applicative.pure(Control_Monad_Aff.applicativeAff)(v.value0);
                            };
                            throw new Error("Failed pattern match at Network.HTTP.Affjax line 227, column 7 - line 231, column 32: " + [ v.constructor.name ]);
                        });
                    };
                };
                return Control_Bind.bind(Control_Monad_Aff.bindAff)(Data_Function.apply(Control_Monad_Eff_Class.liftEff(Control_Monad_Aff.monadEffAff))(Control_Monad_Eff_Ref.newRef(Data_Maybe.Nothing.value)))(function (v) {
                    var loop = go(v);
                    if (policy.timeout instanceof Data_Maybe.Nothing) {
                        return loop(1);
                    };
                    if (policy.timeout instanceof Data_Maybe.Just) {
                        return Control_Bind.bind(Control_Monad_Aff.bindAff)(Control_Monad_Aff_AVar.makeVar)(function (v1) {
                            return Control_Bind.bind(Control_Monad_Aff.bindAff)(Data_Function.apply(Control_Monad_Aff.forkAff)(Control_Bind.bind(Control_Monad_Aff.bindAff)(loop(1))(function ($92) {
                                return Control_Monad_Aff_AVar.putVar(v1)(Data_Maybe.Just.create($92));
                            })))(function (v2) {
                                return Control_Bind.bind(Control_Monad_Aff.bindAff)(Data_Function.apply(function ($93) {
                                    return Control_Monad_Aff.forkAff(Control_Monad_Aff["later'"](policy.timeout.value0)($93));
                                })(Control_Bind.bind(Control_Monad_Aff.bindAff)(Control_Monad_Aff_AVar.putVar(v1)(Data_Maybe.Nothing.value))(function () {
                                    return Control_Monad_Aff.cancel(v2)(Control_Monad_Eff_Exception.error("Cancel"));
                                })))(function (v3) {
                                    return Control_Bind.bind(Control_Monad_Aff.bindAff)(Control_Monad_Aff_AVar.takeVar(v1))(function (v4) {
                                        if (v4 instanceof Data_Maybe.Nothing) {
                                            return Control_Bind.bind(Control_Monad_Aff.bindAff)(Data_Function.apply(Control_Monad_Eff_Class.liftEff(Control_Monad_Aff.monadEffAff))(Control_Monad_Eff_Ref.readRef(v)))(function (v5) {
                                                if (v5 instanceof Data_Maybe.Nothing) {
                                                    return Data_Function.apply(Control_Monad_Error_Class.throwError(Control_Monad_Aff.monadErrorAff))(Control_Monad_Eff_Exception.error("Timeout"));
                                                };
                                                if (v5 instanceof Data_Maybe.Just) {
                                                    return Data_Either.either(Control_Monad_Error_Class.throwError(Control_Monad_Aff.monadErrorAff))(Control_Applicative.pure(Control_Monad_Aff.applicativeAff))(v5.value0);
                                                };
                                                throw new Error("Failed pattern match at Network.HTTP.Affjax line 207, column 11 - line 209, column 61: " + [ v5.constructor.name ]);
                                            });
                                        };
                                        if (v4 instanceof Data_Maybe.Just) {
                                            return Control_Applicative.pure(Control_Monad_Aff.applicativeAff)(v4.value0);
                                        };
                                        throw new Error("Failed pattern match at Network.HTTP.Affjax line 204, column 7 - line 210, column 31: " + [ v4.constructor.name ]);
                                    });
                                });
                            });
                        });
                    };
                    throw new Error("Failed pattern match at Network.HTTP.Affjax line 194, column 3 - line 210, column 31: " + [ policy.timeout.constructor.name ]);
                });
            };
        };
    };
};
var defaultRetryPolicy = {
    timeout: Data_Maybe.Nothing.value, 
    delayCurve: function (n) {
        return Data_Function.apply(Data_Int.round)(Data_Function.apply($$Math.max(30.0 * 1000.0))(100.0 * Data_Function.apply($$Math.pow(2.0))(Data_Int.toNumber(n - 1))));
    }, 
    shouldRetryWithStatusCode: Data_Function["const"](false)
};
var defaultRequest = {
    method: new Data_Either.Left(Data_HTTP_Method_1.GET.value), 
    url: "/", 
    headers: [  ], 
    content: Data_Maybe.Nothing.value, 
    username: Data_Maybe.Nothing.value, 
    password: Data_Maybe.Nothing.value, 
    withCredentials: false
};
var cancelAjax = function (xhr) {
    return function (err) {
        return Control_Monad_Aff.makeAff(function (eb) {
            return function (cb) {
                return $foreign._cancelAjax(xhr, err, eb, cb);
            };
        });
    };
};
var affjax$prime = function (dictRequestable) {
    return function (dictRespondable) {
        return function (req) {
            return function (eb) {
                return function (cb) {
                    var responseSettings = Network_HTTP_Affjax_Response.responseType(dictRespondable);
                    var requestSettings = (function () {
                        var $55 = Data_Functor.map(Data_Maybe.functorMaybe)(Network_HTTP_Affjax_Request.toRequest(dictRequestable))(req.content);
                        if ($55 instanceof Data_Maybe.Nothing) {
                            return new Data_Tuple.Tuple(Data_Maybe.Nothing.value, Data_Maybe.Nothing.value);
                        };
                        if ($55 instanceof Data_Maybe.Just) {
                            return new Data_Tuple.Tuple($55.value0.value0, new Data_Maybe.Just($55.value0.value1));
                        };
                        throw new Error("Failed pattern match at Network.HTTP.Affjax line 258, column 21 - line 260, column 49: " + [ $55.constructor.name ]);
                    })();
                    var fromResponse$prime = (function () {
                        var $59 = Data_Tuple.snd(responseSettings);
                        if ($59 instanceof Network_HTTP_Affjax_Response.JSONResponse) {
                            return Control_Bind.composeKleisliFlipped(Data_Either.bindEither)(Network_HTTP_Affjax_Response.fromResponse(dictRespondable))(Control_Bind.composeKleisliFlipped(Data_Either.bindEither)(Data_Foreign.parseJSON)(Data_Foreign.readString));
                        };
                        return Network_HTTP_Affjax_Response.fromResponse(dictRespondable);
                    })();
                    var cb$prime = function (res) {
                        var $63 = Data_Functor.map(Data_Either.functorEither)(function (v) {
                            var $60 = {};
                            for (var $61 in res) {
                                if (res.hasOwnProperty($61)) {
                                    $60[$61] = res[$61];
                                };
                            };
                            $60.response = v;
                            return $60;
                        })(fromResponse$prime(res.response));
                        if ($63 instanceof Data_Either.Left) {
                            return Data_Function.apply(eb)(Control_Monad_Eff_Exception.error(Data_Show.show(Data_Foreign.showForeignError)($63.value0)));
                        };
                        if ($63 instanceof Data_Either.Right) {
                            return cb($63.value0);
                        };
                        throw new Error("Failed pattern match at Network.HTTP.Affjax line 277, column 13 - line 279, column 26: " + [ $63.constructor.name ]);
                    };
                    var addHeader = function (h) {
                        return function (hs) {
                            if (h instanceof Data_Maybe.Just && Data_Function.apply(Data_HeytingAlgebra.not(Data_HeytingAlgebra.heytingAlgebraBoolean))(Data_Foldable.any(Data_Foldable.foldableArray)(Data_BooleanAlgebra.booleanAlgebraBoolean)(Data_Function.on(Data_Eq.eq(Data_Eq.eqString))(Network_HTTP_RequestHeader.requestHeaderName)(h.value0))(hs))) {
                                return Data_Array.snoc(hs)(h.value0);
                            };
                            return hs;
                        };
                    };
                    var headers = Data_Function.apply(addHeader(Data_Functor.map(Data_Maybe.functorMaybe)(Network_HTTP_RequestHeader.ContentType.create)(Data_Tuple.fst(requestSettings))))(addHeader(Data_Functor.map(Data_Maybe.functorMaybe)(Network_HTTP_RequestHeader.Accept.create)(Data_Tuple.fst(responseSettings)))(req.headers));
                    var req$prime = {
                        method: Data_HTTP_Method_1.print(req.method), 
                        url: req.url, 
                        headers: Data_Functor.map(Data_Functor.functorArray)(function (h) {
                            return {
                                field: Network_HTTP_RequestHeader.requestHeaderName(h), 
                                value: Network_HTTP_RequestHeader.requestHeaderValue(h)
                            };
                        })(headers), 
                        content: Data_Nullable.toNullable(Data_Tuple.snd(requestSettings)), 
                        responseType: Network_HTTP_Affjax_Response.responseTypeToString(Data_Tuple.snd(responseSettings)), 
                        username: Data_Nullable.toNullable(req.username), 
                        password: Data_Nullable.toNullable(req.password), 
                        withCredentials: req.withCredentials
                    };
                    return $foreign._ajax(Network_HTTP_ResponseHeader.responseHeader, req$prime, cancelAjax, eb, cb$prime);
                };
            };
        };
    };
};
var affjax = function (dictRequestable) {
    return function (dictRespondable) {
        return function ($94) {
            return Control_Monad_Aff["makeAff'"](affjax$prime(dictRequestable)(dictRespondable)($94));
        };
    };
};
var $$delete = function (dictRespondable) {
    return function (u) {
        return Data_Function.apply(affjax(Network_HTTP_Affjax_Request.requestableUnit)(dictRespondable))((function () {
            var $68 = {};
            for (var $69 in defaultRequest) {
                if (defaultRequest.hasOwnProperty($69)) {
                    $68[$69] = defaultRequest[$69];
                };
            };
            $68.method = new Data_Either.Left(Data_HTTP_Method_1.DELETE.value);
            $68.url = u;
            return $68;
        })());
    };
};
var delete_ = $$delete(Network_HTTP_Affjax_Response.responsableUnit);
var get = function (dictRespondable) {
    return function (u) {
        return Data_Function.apply(affjax(Network_HTTP_Affjax_Request.requestableUnit)(dictRespondable))((function () {
            var $71 = {};
            for (var $72 in defaultRequest) {
                if (defaultRequest.hasOwnProperty($72)) {
                    $71[$72] = defaultRequest[$72];
                };
            };
            $71.url = u;
            return $71;
        })());
    };
};
var patch = function (dictRequestable) {
    return function (dictRespondable) {
        return function (u) {
            return function (c) {
                return Data_Function.apply(affjax(dictRequestable)(dictRespondable))((function () {
                    var $74 = {};
                    for (var $75 in defaultRequest) {
                        if (defaultRequest.hasOwnProperty($75)) {
                            $74[$75] = defaultRequest[$75];
                        };
                    };
                    $74.method = new Data_Either.Left(Data_HTTP_Method_1.PATCH.value);
                    $74.url = u;
                    $74.content = new Data_Maybe.Just(c);
                    return $74;
                })());
            };
        };
    };
};
var patch_ = function (dictRequestable) {
    return patch(dictRequestable)(Network_HTTP_Affjax_Response.responsableUnit);
};
var patch$prime = function (dictRequestable) {
    return function (dictRespondable) {
        return function (u) {
            return function (c) {
                return Data_Function.apply(affjax(dictRequestable)(dictRespondable))((function () {
                    var $77 = {};
                    for (var $78 in defaultRequest) {
                        if (defaultRequest.hasOwnProperty($78)) {
                            $77[$78] = defaultRequest[$78];
                        };
                    };
                    $77.method = new Data_Either.Left(Data_HTTP_Method_1.PATCH.value);
                    $77.url = u;
                    $77.content = c;
                    return $77;
                })());
            };
        };
    };
};
var patch_$prime = function (dictRequestable) {
    return patch$prime(dictRequestable)(Network_HTTP_Affjax_Response.responsableUnit);
};
var post = function (dictRequestable) {
    return function (dictRespondable) {
        return function (u) {
            return function (c) {
                return Data_Function.apply(affjax(dictRequestable)(dictRespondable))((function () {
                    var $80 = {};
                    for (var $81 in defaultRequest) {
                        if (defaultRequest.hasOwnProperty($81)) {
                            $80[$81] = defaultRequest[$81];
                        };
                    };
                    $80.method = new Data_Either.Left(Data_HTTP_Method_1.POST.value);
                    $80.url = u;
                    $80.content = new Data_Maybe.Just(c);
                    return $80;
                })());
            };
        };
    };
};
var post_ = function (dictRequestable) {
    return post(dictRequestable)(Network_HTTP_Affjax_Response.responsableUnit);
};
var post$prime = function (dictRequestable) {
    return function (dictRespondable) {
        return function (u) {
            return function (c) {
                return Data_Function.apply(affjax(dictRequestable)(dictRespondable))((function () {
                    var $83 = {};
                    for (var $84 in defaultRequest) {
                        if (defaultRequest.hasOwnProperty($84)) {
                            $83[$84] = defaultRequest[$84];
                        };
                    };
                    $83.method = new Data_Either.Left(Data_HTTP_Method_1.POST.value);
                    $83.url = u;
                    $83.content = c;
                    return $83;
                })());
            };
        };
    };
};
var post_$prime = function (dictRequestable) {
    return post$prime(dictRequestable)(Network_HTTP_Affjax_Response.responsableUnit);
};
var put = function (dictRequestable) {
    return function (dictRespondable) {
        return function (u) {
            return function (c) {
                return Data_Function.apply(affjax(dictRequestable)(dictRespondable))((function () {
                    var $86 = {};
                    for (var $87 in defaultRequest) {
                        if (defaultRequest.hasOwnProperty($87)) {
                            $86[$87] = defaultRequest[$87];
                        };
                    };
                    $86.method = new Data_Either.Left(Data_HTTP_Method_1.PUT.value);
                    $86.url = u;
                    $86.content = new Data_Maybe.Just(c);
                    return $86;
                })());
            };
        };
    };
};
var put_ = function (dictRequestable) {
    return put(dictRequestable)(Network_HTTP_Affjax_Response.responsableUnit);
};
var put$prime = function (dictRequestable) {
    return function (dictRespondable) {
        return function (u) {
            return function (c) {
                return Data_Function.apply(affjax(dictRequestable)(dictRespondable))((function () {
                    var $89 = {};
                    for (var $90 in defaultRequest) {
                        if (defaultRequest.hasOwnProperty($90)) {
                            $89[$90] = defaultRequest[$90];
                        };
                    };
                    $89.method = new Data_Either.Left(Data_HTTP_Method_1.PUT.value);
                    $89.url = u;
                    $89.content = c;
                    return $89;
                })());
            };
        };
    };
};
var put_$prime = function (dictRequestable) {
    return put$prime(dictRequestable)(Network_HTTP_Affjax_Response.responsableUnit);
};
module.exports = {
    affjax: affjax, 
    "affjax'": affjax$prime, 
    defaultRequest: defaultRequest, 
    defaultRetryPolicy: defaultRetryPolicy, 
    "delete": $$delete, 
    delete_: delete_, 
    get: get, 
    patch: patch, 
    "patch'": patch$prime, 
    patch_: patch_, 
    "patch_'": patch_$prime, 
    post: post, 
    "post'": post$prime, 
    post_: post_, 
    "post_'": post_$prime, 
    put: put, 
    "put'": put$prime, 
    put_: put_, 
    "put_'": put_$prime, 
    retry: retry
};
