// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var Data_Monoid = require("../Data.Monoid");
var Data_Tuple = require("../Data.Tuple");
var Data_Functor = require("../Data.Functor");
var Control_Apply = require("../Control.Apply");
var Control_Applicative = require("../Control.Applicative");
var Control_Semigroupoid = require("../Control.Semigroupoid");
var Focusing = function (x) {
    return x;
};
var runFocusing = function (v) {
    return v;
};
var focusingFunctor = function (dictFunctor) {
    return new Data_Functor.Functor(function (f) {
        return function (v) {
            return Data_Functor.map(dictFunctor)(Data_Functor.map(Data_Tuple.functorTuple)(f))(v);
        };
    });
};
var focusingApply = function (dictApply) {
    return function (dictSemigroup) {
        return new Control_Apply.Apply(function () {
            return focusingFunctor(dictApply["__superclass_Data.Functor.Functor_0"]());
        }, function (v) {
            return function (v1) {
                return Control_Apply.apply(dictApply)(Data_Functor.map(dictApply["__superclass_Data.Functor.Functor_0"]())(Control_Apply.apply(Data_Tuple.applyTuple(dictSemigroup)))(v))(v1);
            };
        });
    };
};
var focusingApplicative = function (dictApplicative) {
    return function (dictMonoid) {
        return new Control_Applicative.Applicative(function () {
            return focusingApply(dictApplicative["__superclass_Control.Apply.Apply_0"]())(dictMonoid["__superclass_Data.Semigroup.Semigroup_0"]());
        }, function ($14) {
            return Focusing(Control_Applicative.pure(dictApplicative)(Control_Applicative.pure(Data_Tuple.applicativeTuple(dictMonoid))($14)));
        });
    };
};
module.exports = {
    Focusing: Focusing, 
    runFocusing: runFocusing, 
    focusingFunctor: focusingFunctor, 
    focusingApply: focusingApply, 
    focusingApplicative: focusingApplicative
};
