// Generated by psc version 0.9.3
"use strict";
var $foreign = require("./foreign");
var Prelude = require("../Prelude");
var Control_Monad_Eff = require("../Control.Monad.Eff");
var DOM = require("../DOM");
var Control_Bind = require("../Control.Bind");
var Data_Functor = require("../Data.Functor");
var modifyHash = function (fn) {
    return Control_Bind.bind(Control_Monad_Eff.bindEff)(Data_Functor.map(Control_Monad_Eff.functorEff)(fn)($foreign.getHash))($foreign.setHash);
};
module.exports = {
    modifyHash: modifyHash, 
    getHash: $foreign.getHash, 
    setHash: $foreign.setHash
};
