// Generated by psc version 0.9.3
"use strict";
var Default = function (def) {
    this.def = def;
};
var def = function (dict) {
    return dict.def;
};
module.exports = {
    Default: Default, 
    def: def
};
