// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var CSS_Property = require("../CSS.Property");
var CSS_Size = require("../CSS.Size");
var CSS_String = require("../CSS.String");
var CSS_Stylesheet = require("../CSS.Stylesheet");
var Data_Function = require("../Data.Function");
var Data_Semigroup = require("../Data.Semigroup");
var Control_Semigroupoid = require("../Control.Semigroupoid");
var Transformation = function (x) {
    return x;
};
var valTransformation = new CSS_Property.Val(function (v) {
    return v;
});
var translate = function (x) {
    return function (y) {
        return Data_Function.apply(Transformation)(Data_Semigroup.append(CSS_Property.semigroupValue)(CSS_String.fromString(CSS_Property.isStringValue)("translate("))(Data_Semigroup.append(CSS_Property.semigroupValue)(CSS_Property.value(CSS_Property.valList(CSS_Size.valSize))([ x, y ]))(CSS_String.fromString(CSS_Property.isStringValue)(")"))));
    };
};
var transforms = function ($2) {
    return CSS_Stylesheet.key(CSS_Property.valValue)(CSS_String.fromString(CSS_Property.isStringKey)("transform"))(CSS_Property.noCommas(valTransformation)($2));
};
var transform = Data_Function.apply(CSS_Stylesheet.key(valTransformation))(CSS_String.fromString(CSS_Property.isStringKey)("transform"));
var rotate = function (a) {
    return Data_Function.apply(Transformation)(Data_Semigroup.append(CSS_Property.semigroupValue)(CSS_String.fromString(CSS_Property.isStringValue)("rotate("))(Data_Semigroup.append(CSS_Property.semigroupValue)(CSS_Property.value(CSS_Size.valAngle)(a))(CSS_String.fromString(CSS_Property.isStringValue)(")"))));
};
module.exports = {
    Transformation: Transformation, 
    rotate: rotate, 
    transform: transform, 
    transforms: transforms, 
    translate: translate, 
    valTransformation: valTransformation
};
