// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var Data_Lens_Lens = require("../Data.Lens.Lens");
var Data_Function = require("../Data.Function");
var Data_Unit = require("../Data.Unit");
var united = function (dictStrong) {
    return Data_Lens_Lens.lens(Data_Function["const"](Data_Unit.unit))(Data_Function["const"])(dictStrong);
};
module.exports = {
    united: united
};
