// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var Data_Functor_Coproduct = require("../Data.Functor.Coproduct");
var Data_Lens_Iso_Coproduct = require("../Data.Lens.Iso.Coproduct");
var Data_Lens_Prism = require("../Data.Lens.Prism");
var Data_Lens_Prism_Either = require("../Data.Lens.Prism.Either");
var Control_Semigroupoid = require("../Control.Semigroupoid");
var _Right = function (dictChoice) {
    return function ($2) {
        return Data_Lens_Iso_Coproduct._Coproduct(dictChoice["__superclass_Data.Profunctor.Profunctor_0"]())(Data_Lens_Prism_Either._Right(dictChoice)($2));
    };
};
var _Left = function (dictChoice) {
    return function ($3) {
        return Data_Lens_Iso_Coproduct._Coproduct(dictChoice["__superclass_Data.Profunctor.Profunctor_0"]())(Data_Lens_Prism_Either._Left(dictChoice)($3));
    };
};
module.exports = {
    _Left: _Left, 
    _Right: _Right
};
