// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var Data_Profunctor = require("../Data.Profunctor");
var Data_Profunctor_Choice = require("../Data.Profunctor.Choice");
var Data_Profunctor_Cochoice = require("../Data.Profunctor.Cochoice");
var Data_Profunctor_Costrong = require("../Data.Profunctor.Costrong");
var Data_Profunctor_Strong = require("../Data.Profunctor.Strong");
var Control_Semigroupoid = require("../Control.Semigroupoid");
var Re = function (x) {
    return x;
};
var runRe = function (v) {
    return v;
};
var profunctorRe = function (dictProfunctor) {
    return new Data_Profunctor.Profunctor(function (f) {
        return function (g) {
            return function (v) {
                return function ($27) {
                    return v(Data_Profunctor.dimap(dictProfunctor)(g)(f)($27));
                };
            };
        };
    });
};
var strongRe = function (dictStrong) {
    return new Data_Profunctor_Costrong.Costrong(function () {
        return profunctorRe(dictStrong["__superclass_Data.Profunctor.Profunctor_0"]());
    }, function (v) {
        return function ($28) {
            return v(Data_Profunctor_Strong.first(dictStrong)($28));
        };
    }, function (v) {
        return function ($29) {
            return v(Data_Profunctor_Strong.second(dictStrong)($29));
        };
    });
};
var costrongRe = function (dictCostrong) {
    return new Data_Profunctor_Strong.Strong(function () {
        return profunctorRe(dictCostrong["__superclass_Data.Profunctor.Profunctor_0"]());
    }, function (v) {
        return function ($30) {
            return v(Data_Profunctor_Costrong.unfirst(dictCostrong)($30));
        };
    }, function (v) {
        return function ($31) {
            return v(Data_Profunctor_Costrong.unsecond(dictCostrong)($31));
        };
    });
};
var cochoiceRe = function (dictCochoice) {
    return new Data_Profunctor_Choice.Choice(function () {
        return profunctorRe(dictCochoice["__superclass_Data.Profunctor.Profunctor_0"]());
    }, function (v) {
        return function ($32) {
            return v(Data_Profunctor_Cochoice.unleft(dictCochoice)($32));
        };
    }, function (v) {
        return function ($33) {
            return v(Data_Profunctor_Cochoice.unright(dictCochoice)($33));
        };
    });
};
var choiceRe = function (dictChoice) {
    return new Data_Profunctor_Cochoice.Cochoice(function () {
        return profunctorRe(dictChoice["__superclass_Data.Profunctor.Profunctor_0"]());
    }, function (v) {
        return function ($34) {
            return v(Data_Profunctor_Choice.left(dictChoice)($34));
        };
    }, function (v) {
        return function ($35) {
            return v(Data_Profunctor_Choice.right(dictChoice)($35));
        };
    });
};
module.exports = {
    Re: Re, 
    runRe: runRe, 
    profunctorRe: profunctorRe, 
    choiceRe: choiceRe, 
    cochoiceRe: cochoiceRe, 
    strongRe: strongRe, 
    costrongRe: costrongRe
};
