// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var Control_Plus = require("../Control.Plus");
var Data_Array = require("../Data.Array");
var Data_Foldable = require("../Data.Foldable");
var Data_Generic = require("../Data.Generic");
var Data_Int = require("../Data.Int");
var Data_List = require("../Data.List");
var Data_Maybe = require("../Data.Maybe");
var Data_Monoid_Endo = require("../Data.Monoid.Endo");
var Data_Traversable = require("../Data.Traversable");
var Data_Tuple = require("../Data.Tuple");
var Partial_Unsafe = require("../Partial.Unsafe");
var Test_StrongCheck_Arbitrary = require("../Test.StrongCheck.Arbitrary");
var Test_StrongCheck_Gen = require("../Test.StrongCheck.Gen");
var Type_Proxy = require("../Type.Proxy");
var Control_Bind = require("../Control.Bind");
var Data_Function = require("../Data.Function");
var Control_Applicative = require("../Control.Applicative");
var Data_Boolean = require("../Data.Boolean");
var Data_Functor = require("../Data.Functor");
var Control_Monad_Free = require("../Control.Monad.Free");
var Data_Unit = require("../Data.Unit");
var Data_Eq = require("../Data.Eq");
var Data_EuclideanRing = require("../Data.EuclideanRing");
var Data_Semiring = require("../Data.Semiring");
var Control_Semigroupoid = require("../Control.Semigroupoid");
var Data_Ord = require("../Data.Ord");
var Data_Ring = require("../Data.Ring");
var GenericValue = function (x) {
    return x;
};
var runGenericValue = function (v) {
    return v;
};
var genericValue = function (sig) {
    return function (spine) {
        if (Data_Generic.isValidSpine(sig)(spine)) {
            return Data_Function.apply(Data_Maybe.Just.create)({
                signature: sig, 
                spine: spine
            });
        };
        if (Data_Boolean.otherwise) {
            return Data_Maybe.Nothing.value;
        };
        throw new Error("Failed pattern match at Test.StrongCheck.Generic line 71, column 1 - line 73, column 24: " + [ sig.constructor.name, spine.constructor.name ]);
    };
};
var genGenericSpine$prime = function (trail) {
    return function (v) {
        if (v instanceof Data_Generic.SigBoolean) {
            return Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Generic.SBoolean.create)(Test_StrongCheck_Arbitrary.arbitrary(Test_StrongCheck_Arbitrary.arbBoolean));
        };
        if (v instanceof Data_Generic.SigNumber) {
            return Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Generic.SNumber.create)(Test_StrongCheck_Arbitrary.arbitrary(Test_StrongCheck_Arbitrary.arbNumber));
        };
        if (v instanceof Data_Generic.SigInt) {
            return Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Generic.SInt.create)(Test_StrongCheck_Arbitrary.arbitrary(Test_StrongCheck_Arbitrary.arbInt));
        };
        if (v instanceof Data_Generic.SigString) {
            return Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Generic.SString.create)(Test_StrongCheck_Arbitrary.arbitrary(Test_StrongCheck_Arbitrary.arbString));
        };
        if (v instanceof Data_Generic.SigChar) {
            return Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Generic.SChar.create)(Test_StrongCheck_Arbitrary.arbitrary(Test_StrongCheck_Arbitrary.arbChar));
        };
        if (v instanceof Data_Generic.SigUnit) {
            return Control_Applicative.pure(Test_StrongCheck_Gen.applicativeGenT(Control_Monad_Free.freeMonad))(Data_Generic.SUnit.value);
        };
        if (v instanceof Data_Generic.SigArray) {
            return Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Generic.SArray.create)(Test_StrongCheck_Gen.arrayOf(Control_Monad_Free.freeMonad)(Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Function["const"])(genGenericSpine$prime(trail)(v.value0(Data_Unit.unit)))));
        };
        if (v instanceof Data_Generic.SigProd) {
            var trailCount = function (sig) {
                return Data_Function.apply(Data_Array.length)(Data_Array.filter(Data_Eq.eq(Data_Eq.eqString)(sig.sigConstructor))(trail));
            };
            var probability = function (sig) {
                return 6.0 / (5.0 + Data_Int.toNumber(trailCount(sig)));
            };
            var ctors = Data_Functor.mapFlipped(Data_Functor.functorArray)(v.value1)(function (sig) {
                return new Data_Tuple.Tuple(probability(sig), sig);
            });
            var alt = function (altSig) {
                return Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Generic.SProd.create(altSig.sigConstructor))(Data_Traversable.traverse(Data_Traversable.traversableArray)(Test_StrongCheck_Gen.applicativeGenT(Control_Monad_Free.freeMonad))(function ($54) {
                    return Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Function["const"])(genGenericSpine$prime(Data_Array.cons(altSig.sigConstructor)(trail))((function (v1) {
                        return Data_Function.applyFlipped(Data_Unit.unit)(v1);
                    })($54)));
                })(altSig.sigValues));
            };
            return Control_Bind.bindFlipped(Test_StrongCheck_Gen.bindGenT(Control_Monad_Free.freeMonad))(alt)(Data_Maybe.maybe(Control_Plus.empty(Test_StrongCheck_Gen.plusGenT(Control_Monad_Free.freeMonad)))(function (cons) {
                return Test_StrongCheck_Gen.frequency(Control_Monad_Free.freeMonad)(cons.head)(Data_List.fromFoldable(Data_Foldable.foldableArray)(cons.tail));
            })(Data_Function.apply(Data_Array.uncons)(Data_Functor.map(Data_Functor.functorArray)(Data_Functor.map(Data_Tuple.functorTuple)(Control_Applicative.pure(Test_StrongCheck_Gen.applicativeGenT(Control_Monad_Free.freeMonad))))(ctors))));
        };
        if (v instanceof Data_Generic.SigRecord) {
            return Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Generic.SRecord.create)(Data_Traversable["for"](Test_StrongCheck_Gen.applicativeGenT(Control_Monad_Free.freeMonad))(Data_Traversable.traversableArray)(v.value0)(function (field) {
                return Control_Bind.bind(Test_StrongCheck_Gen.bindGenT(Control_Monad_Free.freeMonad))(genGenericSpine$prime(trail)(field.recValue(Data_Unit.unit)))(function (v1) {
                    return Data_Function.apply(Control_Applicative.pure(Test_StrongCheck_Gen.applicativeGenT(Control_Monad_Free.freeMonad)))((function () {
                        var $32 = {};
                        for (var $33 in field) {
                            if (field.hasOwnProperty($33)) {
                                $32[$33] = field[$33];
                            };
                        };
                        $32.recValue = Data_Function["const"](v1);
                        return $32;
                    })());
                });
            }));
        };
        throw new Error("Failed pattern match at Test.StrongCheck.Generic line 104, column 1 - line 104, column 63: " + [ trail.constructor.name, v.constructor.name ]);
    };
};
var genGenericSpine = genGenericSpine$prime(Control_Plus.empty(Control_Plus.plusArray));
var genGenericSignature = function (__copy_v) {
    var v = __copy_v;
    tco: while (true) {
        if (v > 5) {
            v = 5;
            continue tco;
        };
        if (v === 0) {
            return Test_StrongCheck_Gen.elements(Control_Monad_Free.freeMonad)(Data_Generic.SigNumber.value)(Data_List.fromFoldable(Data_Foldable.foldableArray)([ Data_Generic.SigInt.value, Data_Generic.SigString.value, Data_Generic.SigBoolean.value ]));
        };
        var sigRecord = Control_Bind.bind(Test_StrongCheck_Gen.bindGenT(Control_Monad_Free.freeMonad))(Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Array.nub(Data_Eq.eqString))(Test_StrongCheck_Gen.arrayOf(Control_Monad_Free.freeMonad)(Test_StrongCheck_Arbitrary.arbitrary(Test_StrongCheck_Arbitrary.arbString))))(function (v1) {
            return Control_Bind.bind(Test_StrongCheck_Gen.bindGenT(Control_Monad_Free.freeMonad))(Test_StrongCheck_Gen.arrayOf(Control_Monad_Free.freeMonad)(Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Function["const"])(Test_StrongCheck_Gen.sized(Control_Monad_Free.freeMonad)(genGenericSignature))))(function (v2) {
                return Data_Function.apply(Control_Applicative.pure(Test_StrongCheck_Gen.applicativeGenT(Control_Monad_Free.freeMonad)))(Data_Function.apply(Data_Generic.SigRecord.create)(Data_Array.zipWith(function (v3) {
                    return function (v4) {
                        return {
                            recLabel: v3, 
                            recValue: v4
                        };
                    };
                })(v1)(v2)));
            });
        });
        var sigProd = Control_Bind.bind(Test_StrongCheck_Gen.bindGenT(Control_Monad_Free.freeMonad))(Test_StrongCheck_Arbitrary.arbitrary(Test_StrongCheck_Arbitrary.arbString))(function (v1) {
            return Control_Bind.bind(Test_StrongCheck_Gen.bindGenT(Control_Monad_Free.freeMonad))(Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Array.nub(Data_Eq.eqString))(Test_StrongCheck_Gen.arrayOf(Control_Monad_Free.freeMonad)(Test_StrongCheck_Arbitrary.arbitrary(Test_StrongCheck_Arbitrary.arbString))))(function (v2) {
                return Control_Bind.bind(Test_StrongCheck_Gen.bindGenT(Control_Monad_Free.freeMonad))(Test_StrongCheck_Gen.arrayOf(Control_Monad_Free.freeMonad)(Test_StrongCheck_Gen.arrayOf(Control_Monad_Free.freeMonad)(Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(Data_Function["const"])(Test_StrongCheck_Gen.sized(Control_Monad_Free.freeMonad)(genGenericSignature)))))(function (v3) {
                    return Data_Function.apply(Control_Applicative.pure(Test_StrongCheck_Gen.applicativeGenT(Control_Monad_Free.freeMonad)))(Data_Function.apply(Data_Generic.SigProd.create(v1))(Data_Array.zipWith(function (v4) {
                        return function (v5) {
                            return {
                                sigConstructor: v4, 
                                sigValues: v5
                            };
                        };
                    })(v2)(v3)));
                });
            });
        });
        var sigArray = Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(function ($55) {
            return Data_Generic.SigArray.create(Data_Function["const"]($55));
        })(Test_StrongCheck_Gen.sized(Control_Monad_Free.freeMonad)(genGenericSignature));
        return Data_Function.apply(Test_StrongCheck_Gen.resize(Control_Monad_Free.freeMonad)(v - 1))(Test_StrongCheck_Gen.oneOf(Control_Monad_Free.freeMonad)(sigArray)([ sigProd, sigRecord ]));
    };
};
var gArbitrary = function (dictGeneric) {
    return Data_Functor.map(Test_StrongCheck_Gen.functorGenT(Control_Monad_Free.freeMonad))(function ($56) {
        return Partial_Unsafe.unsafePartial(function (dictPartial) {
            return Data_Maybe.fromJust(dictPartial);
        })(Data_Generic.fromSpine(dictGeneric)($56));
    })(genGenericSpine(Data_Generic.toSignature(dictGeneric)((Type_Proxy["Proxy"]).value)));
};
var arbitraryGenericValue = new Test_StrongCheck_Arbitrary.Arbitrary(Control_Bind.bind(Test_StrongCheck_Gen.bindGenT(Control_Monad_Free.freeMonad))(Test_StrongCheck_Gen.sized(Control_Monad_Free.freeMonad)(genGenericSignature))(function (v) {
    return Control_Bind.bind(Test_StrongCheck_Gen.bindGenT(Control_Monad_Free.freeMonad))(genGenericSpine(v))(function (v1) {
        return Data_Function.apply(Data_Maybe.maybe(Control_Plus.empty(Test_StrongCheck_Gen.plusGenT(Control_Monad_Free.freeMonad)))(Control_Applicative.pure(Test_StrongCheck_Gen.applicativeGenT(Control_Monad_Free.freeMonad))))(genericValue(v)(v1));
    });
}));
var applyAll = function (dictFoldable) {
    return function ($57) {
        return Data_Monoid_Endo.runEndo(Data_Foldable.foldMap(dictFoldable)(Data_Monoid_Endo.monoidEndo)(Data_Monoid_Endo.Endo)($57));
    };
};
var gCoarbitrary = function (dictGeneric) {
    var go = function (v) {
        if (v instanceof Data_Generic.SArray) {
            return applyAll(Data_Foldable.foldableArray)(Data_Functor.map(Data_Functor.functorArray)(function ($58) {
                return go((function (v1) {
                    return Data_Function.apply(v1)(Data_Unit.unit);
                })($58));
            })(v.value0));
        };
        if (v instanceof Data_Generic.SBoolean) {
            return Test_StrongCheck_Arbitrary.coarbitrary(Test_StrongCheck_Arbitrary.coarbBoolean)(v.value0);
        };
        if (v instanceof Data_Generic.SString) {
            return Test_StrongCheck_Arbitrary.coarbitrary(Test_StrongCheck_Arbitrary.coarbString)(v.value0);
        };
        if (v instanceof Data_Generic.SChar) {
            return Test_StrongCheck_Arbitrary.coarbitrary(Test_StrongCheck_Arbitrary.coarbChar)(v.value0);
        };
        if (v instanceof Data_Generic.SInt) {
            return Test_StrongCheck_Arbitrary.coarbitrary(Test_StrongCheck_Arbitrary.coarbInt)(v.value0);
        };
        if (v instanceof Data_Generic.SNumber) {
            return Test_StrongCheck_Arbitrary.coarbitrary(Test_StrongCheck_Arbitrary.coarbNumber)(v.value0);
        };
        if (v instanceof Data_Generic.SRecord) {
            return applyAll(Data_Foldable.foldableArray)(Data_Functor.map(Data_Functor.functorArray)(function (f) {
                return function ($59) {
                    return Test_StrongCheck_Arbitrary.coarbitrary(Test_StrongCheck_Arbitrary.coarbString)(f.recLabel)(go(f.recValue(Data_Unit.unit))($59));
                };
            })(v.value0));
        };
        if (v instanceof Data_Generic.SProd) {
            return function ($60) {
                return Test_StrongCheck_Arbitrary.coarbitrary(Test_StrongCheck_Arbitrary.coarbString)(v.value0)(applyAll(Data_Foldable.foldableArray)(Data_Functor.map(Data_Functor.functorArray)(function ($61) {
                    return go((function (v1) {
                        return Data_Function.apply(v1)(Data_Unit.unit);
                    })($61));
                })(v.value1))($60));
            };
        };
        if (v instanceof Data_Generic.SUnit) {
            return Test_StrongCheck_Arbitrary.coarbitrary(Test_StrongCheck_Arbitrary.coarbUnit)(Data_Unit.unit);
        };
        throw new Error("Failed pattern match at Test.StrongCheck.Generic line 43, column 5 - line 43, column 59: " + [ v.constructor.name ]);
    };
    return function ($62) {
        return go(Data_Generic.toSpine(dictGeneric)($62));
    };
};
module.exports = {
    gArbitrary: gArbitrary, 
    gCoarbitrary: gCoarbitrary, 
    genGenericSignature: genGenericSignature, 
    genGenericSpine: genGenericSpine, 
    genericValue: genericValue, 
    runGenericValue: runGenericValue, 
    arbitraryGenericValue: arbitraryGenericValue
};
