// Generated by psc version 0.9.3
"use strict";
var $foreign = require("./foreign");
var Prelude = require("../Prelude");
var Control_Monad_Eff = require("../Control.Monad.Eff");
var Data_StrMap = require("../Data.StrMap");
var Node_Stream = require("../Node.Stream");
var Unsafe_Coerce = require("../Unsafe.Coerce");
var Control_Semigroupoid = require("../Control.Semigroupoid");
var responseAsStream = Unsafe_Coerce.unsafeCoerce;
var requestURL = function ($4) {
    return (function (v) {
        return v.url;
    })(Unsafe_Coerce.unsafeCoerce($4));
};
var requestMethod = function ($5) {
    return (function (v) {
        return v.method;
    })(Unsafe_Coerce.unsafeCoerce($5));
};
var requestHeaders = function ($6) {
    return (function (v) {
        return v.headers;
    })(Unsafe_Coerce.unsafeCoerce($6));
};
var requestAsStream = Unsafe_Coerce.unsafeCoerce;
var httpVersion = function ($7) {
    return (function (v) {
        return v.httpVersion;
    })(Unsafe_Coerce.unsafeCoerce($7));
};
module.exports = {
    httpVersion: httpVersion, 
    requestAsStream: requestAsStream, 
    requestHeaders: requestHeaders, 
    requestMethod: requestMethod, 
    requestURL: requestURL, 
    responseAsStream: responseAsStream, 
    createServer: $foreign.createServer, 
    listen: $foreign.listen, 
    setHeader: $foreign.setHeader, 
    setHeaders: $foreign.setHeaders, 
    setStatusCode: $foreign.setStatusCode, 
    setStatusMessage: $foreign.setStatusMessage
};
