// Generated by psc version 0.9.3
"use strict";
var React = require("../React");
var React_DOM_Props = require("../React.DOM.Props");
var React_DOM = require("../React.DOM");
var wbr = React_DOM.mkDOM(true)("body");
var wbr$prime = wbr([  ]);
var video = React_DOM.mkDOM(true)("video");
var video$prime = video([  ]);
var $$var = React_DOM.mkDOM(true)("var");
var var$prime = $$var([  ]);
var ul = React_DOM.mkDOM(true)("ul");
var ul$prime = ul([  ]);
var u = React_DOM.mkDOM(true)("u");
var u$prime = u([  ]);
var track = React_DOM.mkDOM(true)("track");
var track$prime = track([  ]);
var tr = React_DOM.mkDOM(true)("tr");
var tr$prime = tr([  ]);
var title = React_DOM.mkDOM(true)("title");
var title$prime = title([  ]);
var time = React_DOM.mkDOM(true)("time");
var time$prime = time([  ]);
var thead = React_DOM.mkDOM(true)("thead");
var thead$prime = thead([  ]);
var th = React_DOM.mkDOM(true)("th");
var th$prime = th([  ]);
var tfoot = React_DOM.mkDOM(true)("tfoot");
var tfoot$prime = tfoot([  ]);
var textarea = React_DOM.mkDOM(true)("textarea");
var textarea$prime = textarea([  ]);
var text = React_DOM.text;
var td = React_DOM.mkDOM(true)("td");
var td$prime = td([  ]);
var tbody = React_DOM.mkDOM(true)("tbody");
var tbody$prime = tbody([  ]);
var table = React_DOM.mkDOM(true)("table");
var table$prime = table([  ]);
var sup = React_DOM.mkDOM(true)("sup");
var sup$prime = sup([  ]);
var summary = React_DOM.mkDOM(true)("summary");
var summary$prime = summary([  ]);
var sub = React_DOM.mkDOM(true)("sub");
var sub$prime = sub([  ]);
var style = React_DOM.mkDOM(true)("style");
var style$prime = style([  ]);
var strong = React_DOM.mkDOM(true)("strong");
var strong$prime = strong([  ]);
var span = React_DOM.mkDOM(true)("span");
var span$prime = span([  ]);
var source = React_DOM.mkDOM(true)("source");
var source$prime = source([  ]);
var small = React_DOM.mkDOM(true)("small");
var small$prime = small([  ]);
var select = React_DOM.mkDOM(true)("select");
var select$prime = select([  ]);
var section = React_DOM.mkDOM(true)("section");
var section$prime = section([  ]);
var script = React_DOM.mkDOM(true)("script");
var script$prime = script([  ]);
var samp = React_DOM.mkDOM(true)("samp");
var samp$prime = samp([  ]);
var s = React_DOM.mkDOM(true)("s");
var s$prime = s([  ]);
var ruby = React_DOM.mkDOM(true)("ruby");
var ruby$prime = ruby([  ]);
var rt = React_DOM.mkDOM(true)("rt");
var rt$prime = rt([  ]);
var rp = React_DOM.mkDOM(true)("rp");
var rp$prime = rp([  ]);
var q = React_DOM.mkDOM(true)("q");
var q$prime = q([  ]);
var progress = React_DOM.mkDOM(true)("progress");
var progress$prime = progress([  ]);
var pre = React_DOM.mkDOM(true)("pre");
var pre$prime = pre([  ]);
var picture = React_DOM.mkDOM(true)("picture");
var picture$prime = picture([  ]);
var param = React_DOM.mkDOM(true)("param");
var param$prime = param([  ]);
var p = React_DOM.mkDOM(true)("p");
var p$prime = p([  ]);
var output = React_DOM.mkDOM(true)("output");
var output$prime = output([  ]);
var option = React_DOM.mkDOM(true)("option");
var option$prime = option([  ]);
var optgroup = React_DOM.mkDOM(true)("optgroup");
var optgroup$prime = optgroup([  ]);
var ol = React_DOM.mkDOM(true)("ol");
var ol$prime = ol([  ]);
var object = React_DOM.mkDOM(true)("object");
var object$prime = object([  ]);
var noscript = React_DOM.mkDOM(true)("noscript");
var noscript$prime = noscript([  ]);
var nav = React_DOM.mkDOM(true)("nav");
var nav$prime = nav([  ]);
var meter = React_DOM.mkDOM(true)("meter");
var meter$prime = meter([  ]);
var meta = React_DOM.mkDOM(true)("meta");
var meta$prime = meta([  ]);
var menuitem = React_DOM.mkDOM(true)("menuitem");
var menuitem$prime = menuitem([  ]);
var menu = React_DOM.mkDOM(true)("menu");
var menu$prime = menu([  ]);
var mark = React_DOM.mkDOM(true)("mark");
var mark$prime = mark([  ]);
var map = React_DOM.mkDOM(true)("map");
var map$prime = map([  ]);
var main = React_DOM.mkDOM(true)("main");
var main$prime = main([  ]);
var link = React_DOM.mkDOM(true)("link");
var li = React_DOM.mkDOM(true)("li");
var li$prime = li([  ]);
var legend = React_DOM.mkDOM(true)("legend");
var legend$prime = legend([  ]);
var label = React_DOM.mkDOM(true)("label");
var label$prime = label([  ]);
var keygen = React_DOM.mkDOM(true)("keygen");
var keygen$prime = keygen([  ]);
var kbd = React_DOM.mkDOM(true)("kbd");
var kbd$prime = kbd([  ]);
var ins = React_DOM.mkDOM(true)("ins");
var ins$prime = ins([  ]);
var input = React_DOM.mkDOM(true)("input");
var input$prime = input([  ]);
var img = React_DOM.mkDOM(true)("img");
var img$prime = img([  ]);
var iframe = React_DOM.mkDOM(true)("iframe");
var iframe$prime = iframe([  ]);
var i = React_DOM.mkDOM(true)("i");
var i$prime = i([  ]);
var html = React_DOM.mkDOM(true)("html");
var html$prime = html([  ]);
var hr = React_DOM.mkDOM(true)("hr");
var hr$prime = hr([  ]);
var header = React_DOM.mkDOM(true)("header");
var header$prime = header([  ]);
var head = React_DOM.mkDOM(true)("head");
var head$prime = head([  ]);
var h6 = React_DOM.mkDOM(true)("h6");
var h6$prime = h6([  ]);
var h5 = React_DOM.mkDOM(true)("h5");
var h5$prime = h5([  ]);
var h4 = React_DOM.mkDOM(true)("h4");
var h4$prime = h4([  ]);
var h3 = React_DOM.mkDOM(true)("h3");
var h3$prime = h3([  ]);
var h2 = React_DOM.mkDOM(true)("h2");
var h2$prime = h2([  ]);
var h1 = React_DOM.mkDOM(true)("h1");
var h1$prime = h1([  ]);
var form = React_DOM.mkDOM(true)("form");
var form$prime = form([  ]);
var footer = React_DOM.mkDOM(true)("footer");
var footer$prime = footer([  ]);
var figure = React_DOM.mkDOM(true)("figure");
var figure$prime = figure([  ]);
var figcaption = React_DOM.mkDOM(true)("figcaption");
var figcaption$prime = figcaption([  ]);
var fieldset = React_DOM.mkDOM(true)("fieldset");
var fieldset$prime = fieldset([  ]);
var embed = React_DOM.mkDOM(true)("embed");
var embed$prime = embed([  ]);
var em = React_DOM.mkDOM(true)("em");
var em$prime = em([  ]);
var dt = React_DOM.mkDOM(true)("dt");
var dt$prime = dt([  ]);
var dl = React_DOM.mkDOM(true)("dl");
var dl$prime = dl([  ]);
var div = React_DOM.mkDOM(true)("div");
var div$prime = div([  ]);
var dialog = React_DOM.mkDOM(true)("dialog");
var dialog$prime = dialog([  ]);
var dfn = React_DOM.mkDOM(true)("dfn");
var dfn$prime = dfn([  ]);
var details = React_DOM.mkDOM(true)("details");
var details$prime = details([  ]);
var del = React_DOM.mkDOM(true)("del");
var del$prime = del([  ]);
var dd = React_DOM.mkDOM(true)("dd");
var dd$prime = dd([  ]);
var datalist = React_DOM.mkDOM(true)("datalist");
var datalist$prime = datalist([  ]);
var colgroup = React_DOM.mkDOM(true)("colgroup");
var colgroup$prime = colgroup([  ]);
var col = React_DOM.mkDOM(true)("col");
var col$prime = col([  ]);
var code = React_DOM.mkDOM(true)("code");
var code$prime = code([  ]);
var cite = React_DOM.mkDOM(true)("cite");
var cite$prime = cite([  ]);
var caption = React_DOM.mkDOM(true)("caption");
var caption$prime = caption([  ]);
var canvas = React_DOM.mkDOM(true)("canvas");
var canvas$prime = canvas([  ]);
var button = React_DOM.mkDOM(true)("button");
var button$prime = button([  ]);
var br = React_DOM.mkDOM(true)("br");
var br$prime = br([  ]);
var body = React_DOM.mkDOM(true)("body");
var body$prime = body([  ]);
var link$prime = body([  ]);
var blockquote = React_DOM.mkDOM(true)("blockquote");
var blockquote$prime = blockquote([  ]);
var big = React_DOM.mkDOM(true)("big");
var big$prime = big([  ]);
var bdo = React_DOM.mkDOM(true)("bdo");
var bdo$prime = bdo([  ]);
var bdi = React_DOM.mkDOM(true)("bdi");
var bdi$prime = bdi([  ]);
var base = React_DOM.mkDOM(true)("base");
var base$prime = base([  ]);
var b = React_DOM.mkDOM(true)("b");
var b$prime = b([  ]);
var audio = React_DOM.mkDOM(true)("audio");
var audio$prime = audio([  ]);
var aside = React_DOM.mkDOM(true)("aside");
var aside$prime = aside([  ]);
var article = React_DOM.mkDOM(true)("article");
var article$prime = article([  ]);
var area = React_DOM.mkDOM(true)("area");
var area$prime = area([  ]);
var address = React_DOM.mkDOM(true)("address");
var address$prime = address([  ]);
var abbr = React_DOM.mkDOM(true)("abbr");
var abbr$prime = abbr([  ]);
var a = React_DOM.mkDOM(true)("a");
var a$prime = a([  ]);
var _data = React_DOM.mkDOM(true)("data");
var _data$prime = _data([  ]);
module.exports = {
    _data: _data, 
    "_data'": _data$prime, 
    a: a, 
    "a'": a$prime, 
    abbr: abbr, 
    "abbr'": abbr$prime, 
    address: address, 
    "address'": address$prime, 
    area: area, 
    "area'": area$prime, 
    article: article, 
    "article'": article$prime, 
    aside: aside, 
    "aside'": aside$prime, 
    audio: audio, 
    "audio'": audio$prime, 
    b: b, 
    "b'": b$prime, 
    base: base, 
    "base'": base$prime, 
    bdi: bdi, 
    "bdi'": bdi$prime, 
    bdo: bdo, 
    "bdo'": bdo$prime, 
    big: big, 
    "big'": big$prime, 
    blockquote: blockquote, 
    "blockquote'": blockquote$prime, 
    body: body, 
    "body'": body$prime, 
    br: br, 
    "br'": br$prime, 
    button: button, 
    "button'": button$prime, 
    canvas: canvas, 
    "canvas'": canvas$prime, 
    caption: caption, 
    "caption'": caption$prime, 
    cite: cite, 
    "cite'": cite$prime, 
    code: code, 
    "code'": code$prime, 
    col: col, 
    "col'": col$prime, 
    colgroup: colgroup, 
    "colgroup'": colgroup$prime, 
    datalist: datalist, 
    "datalist'": datalist$prime, 
    dd: dd, 
    "dd'": dd$prime, 
    del: del, 
    "del'": del$prime, 
    details: details, 
    "details'": details$prime, 
    dfn: dfn, 
    "dfn'": dfn$prime, 
    dialog: dialog, 
    "dialog'": dialog$prime, 
    div: div, 
    "div'": div$prime, 
    dl: dl, 
    "dl'": dl$prime, 
    dt: dt, 
    "dt'": dt$prime, 
    em: em, 
    "em'": em$prime, 
    embed: embed, 
    "embed'": embed$prime, 
    fieldset: fieldset, 
    "fieldset'": fieldset$prime, 
    figcaption: figcaption, 
    "figcaption'": figcaption$prime, 
    figure: figure, 
    "figure'": figure$prime, 
    footer: footer, 
    "footer'": footer$prime, 
    form: form, 
    "form'": form$prime, 
    h1: h1, 
    "h1'": h1$prime, 
    h2: h2, 
    "h2'": h2$prime, 
    h3: h3, 
    "h3'": h3$prime, 
    h4: h4, 
    "h4'": h4$prime, 
    h5: h5, 
    "h5'": h5$prime, 
    h6: h6, 
    "h6'": h6$prime, 
    head: head, 
    "head'": head$prime, 
    header: header, 
    "header'": header$prime, 
    hr: hr, 
    "hr'": hr$prime, 
    html: html, 
    "html'": html$prime, 
    i: i, 
    "i'": i$prime, 
    iframe: iframe, 
    "iframe'": iframe$prime, 
    img: img, 
    "img'": img$prime, 
    input: input, 
    "input'": input$prime, 
    ins: ins, 
    "ins'": ins$prime, 
    kbd: kbd, 
    "kbd'": kbd$prime, 
    keygen: keygen, 
    "keygen'": keygen$prime, 
    label: label, 
    "label'": label$prime, 
    legend: legend, 
    "legend'": legend$prime, 
    li: li, 
    "li'": li$prime, 
    link: link, 
    "link'": link$prime, 
    main: main, 
    "main'": main$prime, 
    map: map, 
    "map'": map$prime, 
    mark: mark, 
    "mark'": mark$prime, 
    menu: menu, 
    "menu'": menu$prime, 
    menuitem: menuitem, 
    "menuitem'": menuitem$prime, 
    meta: meta, 
    "meta'": meta$prime, 
    meter: meter, 
    "meter'": meter$prime, 
    nav: nav, 
    "nav'": nav$prime, 
    noscript: noscript, 
    "noscript'": noscript$prime, 
    object: object, 
    "object'": object$prime, 
    ol: ol, 
    "ol'": ol$prime, 
    optgroup: optgroup, 
    "optgroup'": optgroup$prime, 
    option: option, 
    "option'": option$prime, 
    output: output, 
    "output'": output$prime, 
    p: p, 
    "p'": p$prime, 
    param: param, 
    "param'": param$prime, 
    picture: picture, 
    "picture'": picture$prime, 
    pre: pre, 
    "pre'": pre$prime, 
    progress: progress, 
    "progress'": progress$prime, 
    q: q, 
    "q'": q$prime, 
    rp: rp, 
    "rp'": rp$prime, 
    rt: rt, 
    "rt'": rt$prime, 
    ruby: ruby, 
    "ruby'": ruby$prime, 
    s: s, 
    "s'": s$prime, 
    samp: samp, 
    "samp'": samp$prime, 
    script: script, 
    "script'": script$prime, 
    section: section, 
    "section'": section$prime, 
    select: select, 
    "select'": select$prime, 
    small: small, 
    "small'": small$prime, 
    source: source, 
    "source'": source$prime, 
    span: span, 
    "span'": span$prime, 
    strong: strong, 
    "strong'": strong$prime, 
    style: style, 
    "style'": style$prime, 
    sub: sub, 
    "sub'": sub$prime, 
    summary: summary, 
    "summary'": summary$prime, 
    sup: sup, 
    "sup'": sup$prime, 
    table: table, 
    "table'": table$prime, 
    tbody: tbody, 
    "tbody'": tbody$prime, 
    td: td, 
    "td'": td$prime, 
    text: text, 
    textarea: textarea, 
    "textarea'": textarea$prime, 
    tfoot: tfoot, 
    "tfoot'": tfoot$prime, 
    th: th, 
    "th'": th$prime, 
    thead: thead, 
    "thead'": thead$prime, 
    time: time, 
    "time'": time$prime, 
    title: title, 
    "title'": title$prime, 
    tr: tr, 
    "tr'": tr$prime, 
    track: track, 
    "track'": track$prime, 
    u: u, 
    "u'": u$prime, 
    ul: ul, 
    "ul'": ul$prime, 
    "var": $$var, 
    "var'": var$prime, 
    video: video, 
    "video'": video$prime, 
    wbr: wbr, 
    "wbr'": wbr$prime
};
