// Generated by psc version 0.9.3
"use strict";
var $foreign = require("./foreign");
var Prelude = require("../Prelude");
var Control_Monad_Eff = require("../Control.Monad.Eff");
var DOM = require("../DOM");
module.exports = {
    mkSongFullscreen: $foreign.mkSongFullscreen
};
