// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var CSS_Color = require("../CSS.Color");
var CSS_Common = require("../CSS.Common");
var CSS_Property = require("../CSS.Property");
var CSS_Stylesheet = require("../CSS.Stylesheet");
var CSS_Size = require("../CSS.Size");
var CSS_String = require("../CSS.String");
var CSS_Border = require("../CSS.Border");
var Control_Semigroupoid = require("../Control.Semigroupoid");
var Data_Function = require("../Data.Function");
var Data_Semigroup = require("../Data.Semigroup");
var Data_Tuple = require("../Data.Tuple");
var BoxType = function (x) {
    return x;
};
var valBoxType = new CSS_Property.Val(function (v) {
    return v;
});
var paddingBox = Data_Function.apply(BoxType)(CSS_String.fromString(CSS_Property.isStringValue)("padding-box"));
var isStringBoxType = new CSS_String.IsString(function ($2) {
    return BoxType(CSS_String.fromString(CSS_Property.isStringValue)($2));
});
var insetBoxShadow = function (x) {
    return function (y) {
        return function (w) {
            return function (c) {
                return function (z) {
                    return CSS_Stylesheet.prefixed(CSS_Property.valTuple(CSS_Border.valStroke)(CSS_Property.valTuple(CSS_Size.valSize)(CSS_Property.valTuple(CSS_Size.valSize)(CSS_Property.valTuple(CSS_Size.valSize)(CSS_Property.valColor)))))(Data_Semigroup.append(CSS_Property.semigroupPrefixed)(CSS_Common.browsers)(CSS_String.fromString(CSS_Property.isStringPrefixed)("box-shadow")))(new Data_Tuple.Tuple(x, new Data_Tuple.Tuple(y, new Data_Tuple.Tuple(w, new Data_Tuple.Tuple(c, z)))));
                };
            };
        };
    };
};
var inheritBoxType = new CSS_Common.Inherit(CSS_String.fromString(isStringBoxType)("inherit"));
var contentBox = Data_Function.apply(BoxType)(CSS_String.fromString(CSS_Property.isStringValue)("content-box"));
var boxSizing = Data_Function.apply(CSS_Stylesheet.key(valBoxType))(CSS_String.fromString(CSS_Property.isStringKey)("box-sizing"));
var boxShadow = function (x) {
    return function (y) {
        return function (w) {
            return function (c) {
                return CSS_Stylesheet.prefixed(CSS_Property.valTuple(CSS_Size.valSize)(CSS_Property.valTuple(CSS_Size.valSize)(CSS_Property.valTuple(CSS_Size.valSize)(CSS_Property.valColor))))(Data_Semigroup.append(CSS_Property.semigroupPrefixed)(CSS_Common.browsers)(CSS_String.fromString(CSS_Property.isStringPrefixed)("box-shadow")))(new Data_Tuple.Tuple(x, new Data_Tuple.Tuple(y, new Data_Tuple.Tuple(w, c))));
            };
        };
    };
};
var borderBox = Data_Function.apply(BoxType)(CSS_String.fromString(CSS_Property.isStringValue)("border-box"));
module.exports = {
    borderBox: borderBox, 
    boxShadow: boxShadow, 
    boxSizing: boxSizing, 
    contentBox: contentBox, 
    insetBoxShadow: insetBoxShadow, 
    paddingBox: paddingBox, 
    isStringBoxType: isStringBoxType, 
    valBoxType: valBoxType, 
    inheritBoxType: inheritBoxType
};
