// Generated by psc version 0.9.3
"use strict";
var Prelude = require("../Prelude");
var Data_NonEmpty = require("../Data.NonEmpty");
var CSS_Color = require("../CSS.Color");
var CSS_Property = require("../CSS.Property");
var CSS_Size = require("../CSS.Size");
var CSS_String = require("../CSS.String");
var CSS_Stylesheet = require("../CSS.Stylesheet");
var Data_Function = require("../Data.Function");
var Control_Semigroupoid = require("../Control.Semigroupoid");
var Data_Semigroup = require("../Data.Semigroup");
var Data_Functor = require("../Data.Functor");
var Control_Alternative = require("../Control.Alternative");
var GenericFontFamily = function (x) {
    return x;
};
var FontWeight = function (x) {
    return x;
};
var weight = function (i) {
    return Data_Function.apply(FontWeight)(CSS_Property.value(CSS_Property.valNumber)(i));
};
var valGenericFontFamily = new CSS_Property.Val(function (v) {
    return v;
});
var valFontWeight = new CSS_Property.Val(function (v) {
    return v;
});
var sansSerif = Data_Function.apply(GenericFontFamily)(CSS_String.fromString(CSS_Property.isStringValue)("sans-serif"));
var lighter = Data_Function.apply(FontWeight)(CSS_String.fromString(CSS_Property.isStringValue)("lighter"));
var fontWeight = Data_Function.apply(CSS_Stylesheet.key(valFontWeight))(CSS_String.fromString(CSS_Property.isStringKey)("font-weight"));
var fontSize = Data_Function.apply(CSS_Stylesheet.key(CSS_Size.valSize))(CSS_String.fromString(CSS_Property.isStringKey)("font-size"));
var fontFamily = function (a) {
    return function (b) {
        return Data_Function.apply(function ($4) {
            return CSS_Stylesheet.key(CSS_Property.valValue)(CSS_String.fromString(CSS_Property.isStringKey)("font-family"))(CSS_Property.value(CSS_Property.valList(CSS_Property.valValue))($4));
        })(Data_Semigroup.append(Data_Semigroup.semigroupArray)(Data_Functor.map(Data_Functor.functorArray)(function ($5) {
            return CSS_Property.value(CSS_Property.valString)(CSS_Property.quote($5));
        })(a))(Data_NonEmpty.oneOf(Control_Alternative.alternativeArray)(Data_Functor.map(Data_NonEmpty.functorNonEmpty(Data_Functor.functorArray))(CSS_Property.value(valGenericFontFamily))(b))));
    };
};
var color = Data_Function.apply(CSS_Stylesheet.key(CSS_Property.valColor))(CSS_String.fromString(CSS_Property.isStringKey)("color"));
var bolder = Data_Function.apply(FontWeight)(CSS_String.fromString(CSS_Property.isStringValue)("bolder"));
var bold = Data_Function.apply(FontWeight)(CSS_String.fromString(CSS_Property.isStringValue)("bold"));
module.exports = {
    FontWeight: FontWeight, 
    GenericFontFamily: GenericFontFamily, 
    bold: bold, 
    bolder: bolder, 
    color: color, 
    fontFamily: fontFamily, 
    fontSize: fontSize, 
    fontWeight: fontWeight, 
    lighter: lighter, 
    sansSerif: sansSerif, 
    weight: weight, 
    valGenericFontFamily: valGenericFontFamily, 
    valFontWeight: valFontWeight
};
